name: Deploy MultiDocker

on:
  push:
    branches:
      - master # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test React app
        run: |
          docker build -t katramms/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true katramms/react-test npm test

      - name: Build Docker images
        run: |
          docker build -t katramms/multi-client ./client
          docker build -t katramms/multi-nginx ./nginx
          docker build -t katramms/multi-server ./server
          docker build -t katramms/multi-worker ./worker

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Verify Docker Authentication
        run: docker info

      - name: Push Docker images to Docker Hub
        run: |
          docker push katramms/multi-client
          docker push katramms/multi-nginx
          docker push katramms/multi-server
          docker push katramms/multi-worker

      - name: Log out of Docker Hub
        run: docker logout
